language: csharp
dist: trusty

sudo: false  # use the new container-based Travis infrastructure

services:
  - postgres

addons:
  postgresql: "9.5"
  
mono:
  - 5.0.1

os:
  - linux
  - osx
  
before_script:
  # Fixes PostgreSQL not starting on OSX. See https://github.com/travis-ci/travis-ci/issues/1875#issuecomment-263847183
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf /usr/local/var/postgres; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then initdb /usr/local/var/postgres; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pg_ctl -D /usr/local/var/postgres start; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then until createuser -s postgres; do echo "Postgres is unavailable - sleeping"; sleep 0.05; done; fi

script:
  - ./build.sh All

branches:
  except:
  - gh-pages